# old setting start
# CONFIG_ZMK_MOUSE=y
# CONFIG_SPI=y
# CONFIG_INPUT=y

# # CONFIG_ZMK_USB_LOGGING=y

# # PMW3610 Driver
# # CONFIG_PINCTRL=y
# # CONFIG_GPIO=y
# CONFIG_SPI=y
# # CONFIG_INPUT=y
# CONFIG_PMW3610=y

# # CONFIG_ZMK_STUDIO=y
# # CONFIG_ZMK_STUDIO_LOCKING=n

# # Go to sleep after 15 mins (15*60*1000ms)
# # CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
# # CONFIG_ZMK_SLEEP=y
# old setting end

# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_TIMEOUT=300000
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
# CONFIG_ZMK_BATTERY_REPORTING=y
# CONFIG_ZMK_EXT_POWER=y

# CONFIG_ZMK_STUDIO=y
# CONFIG_ZMK_STUDIO_LOCKING=n

# CONFIG_SPI=y
# CONFIG_INPUT=y
# CONFIG_PMW3610=y
# CONFIG_ZMK_MOUSE=y

# CONFIG_PMW3610_SWAP_XY=y
# CONFIG_PMW3610_INVERT_X=n
# CONFIG_PMW3610_INVERT_Y=n
# #CONFIG_PMW3610_REPORT_INTERVAL_MIN=12
# CONFIG_PMW3610_REST1_SAMPLE_TIME_MS=100
# CONFIG_PMW3610_REST2_SAMPLE_TIME_MS=200
# CONFIG_PMW3610_REST3_SAMPLE_TIME_MS=300
# CONFIG_PMW3610_RUN_DOWNSHIFT_TIME_MS=500
# CONFIG_PMW3610_REST1_DOWNSHIFT_TIME_MS=3000
# CONFIG_PMW3610_REST2_DOWNSHIFT_TIME_MS=30000


CONFIG_ZMK_KEYBOARD_NAME="thewolfmouse"

CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# CONFIG_ZMK_STUDIO=y
# CONFIG_ZMK_STUDIO_LOCKING=n

# Turn on mouse key
CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y
CONFIG_GPIO=y

# PMW3610 Driver
CONFIG_PINCTRL=y
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_PMW3610=y
CONFIG_PMW3610_SWAP_XY=y
CONFIG_PMW3610_INVERT_X=y
# CONFIG_PMW3610_INVERT_Y=y
# CONFIG_PMW3610_REPORT_INTERVAL_MIN=12
# CONFIG_PMW3610_LOG_LEVEL_DBG=y
CONFIG_PMW3610_INIT_POWER_UP_EXTRA_DELAY_MS=3000

# Enable encode
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
# CONFIG_NFCT_PINS_AS_GPIOS=y

# +8 dBm
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Go to sleep after 15 mins (15*60*1000ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_SLEEP=y

# Clear settings on start
# CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=y

# Allow second peripheral (for pairing trackball peripheral)
#  NOTE:
#   #define ZMK_BLE_PROFILE_COUNT (CONFIG_BT_MAX_PAIRED - CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS)
#   #define ZMK_SPLIT_BLE_PERIPHERAL_COUNT CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS
CONFIG_BT_MAX_PAIRED=3